workspace:
    base: /go
    path: src/github.com/go-training

clone:
    git:
        image: plugins/git
        depth: 50
        tags: true

pipeline:
    testing:
        image: golang:1.12.0
        commands:
            - go test -v .
            - go vet


build_linux_amd64:
    image: golang:1.12.0
    group: build
    commands:
        - make build_linux_amd64

build_linux_i386:
    image: golang:1.12.0
    group: build
    commands:
        - make build_linux_i386

pubic_linux_amd64:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    auto_tag: true
    dockerfile: Dockerfile
    when:
        event: [ push, tag ]
        local: false

pubic_alpine:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: ${DRONE_REPO}
    default_tags: true
    default_suffix: alpine
    dockerfile: Dockerfile.alpine
    when:
        event: [ push, tag ]
        local: false