workspace:
    base: /go
    path: src/github.com/go-training

clone:
    git:
        image: plugins/git
        depth: 50
        tags: true

pipeline:
    testing:
        image: golang:1.12.0
        command:
            - go test -v .
            - go vet